## Example Config file
BaseURL: "example.com"
theme: "terminalcv"
title: "The janitor's closet"

params:
  description: "div"
  prompt: "Div@topsecretserver"
  promptColor: Lavender
  promptSimbols: ":~$"
  promptSimbolsColor: Lavender
  startxLocation: https://www.youtube.com/watch?v=dQw4w9WgXcQ
# hideSocialName: true
  exitLocation:  https://emu.team/
  hidesource: true

  greeting: | 
  

    Welcome to the janitor's closet

            ;                                                                                                            
            ED.                                                                                                          
            E#Wi                        .           .                .        ,;                            ,;           
            E###G.       t              EK,        ;W               ;W      f#i j.                        f#i j.         
            E#fD#W;      Ej             .j;       f#E              f#E    .E#t  EW,                     .E#t  EW,        
            E#t t##L     E#, t      .DD.        .E#f             .E#f    i#W,   E##j       t      .DD. i#W,   E##j       
            E#t  .E#K,   E#t EK:   ,WK.        iWW;             iWW;    L#D.    E###D.     EK:   ,WK. L#D.    E###D.     
            E#t    j##f  E#t E#t  i#D         L##Lffi          L##Lffi:K#Wfff;  E#jG#W;    E#t  i#D :K#Wfff;  E#jG#W;    
            E#t    :E#K: E#t E#t j#f         tLLG##L          tLLG##L i##WLLLLt E#t t##f   E#t j#f  i##WLLLLt E#t t##f   
            E#t   t##L   E#t E#tL#i            ,W#i             ,W#i   .E#L     E#t  :K#E: E#tL#i    .E#L     E#t  :K#E: 
            E#t .D#W;    E#t E#WW,            j#E.             j#E.      f#E:   E#KDDDD###iE#WW,       f#E:   E#KDDDD###i
            E#tiW#G.     E#t E#K:           .D#j             .D#j         ,WW;  E#f,t#Wi,,,E#K:         ,WW;  E#f,t#Wi,,,
            E#K##i       E#t ED.           ,WK,             ,WK,           .D#; E#t  ;#W:  ED.           .D#; E#t  ;#W:  
            E##D.        E#t t             EG.              EG.              tt DWi   ,KK: t               tt DWi   ,KK: 
            E#t          ,;.               ,                ,                                                            
            L:                                                                                                           

                                                                                                                                                                                                                                    
    Type 'help' for a list of available commands


  whois: 
      name: "Div B"
      profession: "Unknown"
      location: "Perth"
      email: "contact-divB@proton.me"
      homelink: "https://divsforensics.com"
      description: |

              Hi, my name is </Div>, and I am currently studying at The University of Western Australia.
              I like digital forensics, le memez, socioeconomic and political issues. 



  social:
    ## IF you want to keep them aligned just add spaces


    
    - name: "github"
      url: "          https://github.com/DBprassan12"
    - name: "linkedin"
      url: "        https://www.linkedin.com/in/div-cyber"





  work:

    - jobTitle: Cybersecurity Engineer (Internship) 
      color: Lavender
      company: 'Wesfarmers Chemicals, Energy & Fertilisers ' 
      location: Perth AU
      date: November 2023 - February 2024
      description: | 

              Responsibilities
              
              - Collaborate with stakeholders to understand security needs.
              - Ensure effective integration of security measures into the existing infrastructure.
              - Set up systems for real-time web traffic monitoring.
              - Track IP addresses, data packets, and user behavior.
              - Detect patterns that deviate from the norm, indicating potential threats.
              - Keep detailed logs of web traffic.
              - Collect and analyze data from various sources and audit file systems.


    - jobTitle: Digital Forensics and Incident Response Analyst (Internship) 
      color: Lavender
      company: 'Australian Public Service [REDACTED] ' 
      location: Perth AU
      date: November 2021 - February 2023
      description: | 

              Responsibilities

              - Assist in monitoring and detecting security incidents
              - Support the Incident Response team in analyzing and investigating security incidents to determine
               the cause, scope, and impact of the incident
              - Help develop and implement security measures to protect APS systems and data
              - Contribute to risk assessments to identify vulnerabilities and recommend security improvements
              - Assist in containing, eradicating, and recovering from security incidents
              - Participate in security training to develop your knowledge and skills
              - Stay up-to-date with the latest security technologies, trends, and threats


    - jobTitle: Cyber Security Analyst
      color: Lavender
      company: 'Slipstream Cyber' 
      location: Perth Australia 
      date: March 2019 - May 2021
      description: |

            Responsibilities

            - Monitor security systems and networks to identify security threats and incidents
            - Investigate security incidents to determine the cause, scope, and impact of the incident
            - Develop and implement security measures to protect the organization's systems and data
            - Conduct risk assessments to identify vulnerabilities and recommend security improvements
            - Respond to security incidents by containing, eradicating, and recovering from the incident
            - Provide security guidance and training to other personnel in the organization
            - Stay up-to-date with the latest security technologies, trends, and threats



  extracurricular:


    - commitments : ACSS Delegate
      color: Lavender
      club: 'Australian Crisis Simulation Summit' 
      url: https://australiancrisissimulationsummit.com/
      location: Canberra Australia 
      date: September 2023
      description: |
        The Australian Crisis Simulation Summit (ACSS) at ANU is a student-run volunteer organization. 
        It focuses on complex future-based crisis simulations to develop future national security leaders. 
        ACSS embraces a multidisciplinary approach, involving diverse voices and participants from non-security fields.


    - commitments :  (OCM) - coders for causes
      color: Lavender
      club: 'coders for causes' 
      url: https://codersforcauses.org/
      location: Perth Australia 
      date: March 2021/2022  & 2023/2024
      description: |
        Coders for Causes are a group of developers that empower charities and non-profit organisations 
        by providing them solutions to their technical problems. 
        We are student powered and all of our members are volunteers dedicated to providing you the best results.


    - commitments : Tech and Ops Lead - UWA Venture Student Innovation Centre
      color: Lavender
      club: 'UWA Venture Student Innovation Centre' 
      url: https://www.venture-student-innovation.com
      location: Perth Australia 
      date: 2021- Present 
      description: |
          Venture is a student led organisation creating opportunities for students to develop enterprise 
          and innovation skills, build capability and grow networks. 
          We believe this is the key to future-proofing careers, resilient to the rapidly changing economy. 


    - commitments :  Perth Socialware organizer & CTF player
      color: Lavender
      club: 'Emu Exploit' 
      url: https://emu.team
      location: Perth Australia 
      date:  may 2022 - 2024
      description: |
          Emu Exploit, formerly PissedEmu, is Australia’s top Competitive Hacking team. Based in Perth WA, 
          the team has 2 years experience capturing flags (Founded 2021).


    - commitments : Vice President- UWA information Security Society 
      color: Lavender
      club: 'UWA information Security Society' 
      url: https://au.linkedin.com/company/uwa-information-security-society 
      location: Perth Australia 
      date: Oct 2021- Present 
      description: |
          UWA Information Security Society is a student club located at the University Of Western Australia 
          that aims to promote Cyber Security legally and ethically. 
          Our goal is to foster the next generation of information security professionals by creating and 
          participating in capture the flag (CTF) events and information security research.



  education:

   - courseName: Bachelor of Arts - Major in Political Science and International Relations
     color: Lavender
     institute: The University of Western Australia
     date: 2023- present
     description: |

   - courseName: Bachelor of Science - Major in Cyber security [discontinued]
     color: Lavender
     institute: The University of Western Australia
     date: 2021- 2023
     description: |


   - courseName: Advance Diploma of Cyber Security
     color: Lavender
     institute: South Metropolitan TAFE ( Murdoch)
     date: 2019- 2020
     description: |


   - courseName: Cert IV in Information Technology Networking
     color: Lavender
     institute: South Metropolitan TAFE ( Murdoch)
     date: 2018- 2019
     description: |


   - courseName: Cert IV in Cybersecurity
     color: Lavender
     institute: South Metropolitan TAFE ( Murdoch)
     date: 2018- 2018
     description: |



  projects:


    - title: -Windows69 Chat-Bot
      color: MediumSpringGreen
      date: 2023
      status: Done
      link: https://github.com/CITS3403GroupProject/Windows69-Chatbot

      description: |
            Experience the nostalgia of Windows 98 with real-time chats and customizable AI chatbots. 
            Discover the unique personalities of your AI companions and even chat with a modernized Clippy! 
            This platform blends advanced AI with a vintage graphical interface to offer an immersive, 
            memorable experience reminiscent of the late 90s.

        
    - title: -DUCTF 5 MEME
      color: MediumSpringGreen
      date: 2024
      status: Done
      link: https://dbprassan12.github.io/DUCTFMEM2.0

      description: |
            "HexBit Ransom Page , Capturing the essence of DUCTF 2024"


    - title: -DUCTF 4 MEME (WINNER 2023)
      color: MediumSpringGreen
      date: 2023
      status: Done
      link: https://dbprassan12.github.io/DUCTF4MEME/

      description: |
            "Carefully crafted, magnificent eye for detail and true attention to audio. Capturing the essence of DUCTF 2023"
       

    - title: -Velociraptor quick Deployment kit
      color: MediumSpringGreen
      date: Started 2023
      status: In progress
      link: https://github.com/DBprassan12/-Velociraptor-Deploy

      description: |
            Velociraptor advanced digital forensic and response tool quick deployment kit

  



  certifications:

  - certName: GIAC Certified Forensic Analyst (GCFA) & FOR508
    company: 'SANS Institute & GIAC'
    date: 2024

  - certName: FOR500 Windows Forensic Analysis 
    company: 'SANS Institute'
    date: 2022

  - certName: Siemplify Certified SOAR Analyst 
    company: Siemplify
    date: 2020

  - certName: Siemplify Platform Fundamentals
    company: Siemplify
    date: 2020

  - certName: CB Defence Associate Analyst
    company: VMware Carbon BlackVMware Carbon Black 
    date: 2019
  


  misc: 
    #commandName: newcommand
    title: "Pottery addict"
    titleColor: MediumSpringGreen
    content: |
              I LIKE MAKING POT AND MUGS 
   

    contentColor: white



